<a href="https://colab.research.google.com/github/hameedjimoh312/Coding-School/blob/main/Research_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [11]:
url = "https://raw.githubusercontent.com/frontiertechinstitute/datasets/refs/heads/main/Passwords/sampled_passwords.csv"

df = pd.read_csv(url)

In [14]:

df.head()

                        Password  Strength_Level
0                   abrocomeLlll               1
1       EZ&c%{(1~;eu7a/uUGL&B}%Z               4
2  ]|VWl>90|3\]dL~_y*fOQa$5Q~?2q               4
3                   accordancyy]               2
4                          xjemt               0

In [27]:
df["Strength_Level"].value_counts()
df["Password"].duplicated()

0          False
1          False
2          False
3          False
4          False
           ...
1500107    False
1500108    False
1500109    False
1500110    False
1500111    False
Name: Password, Length: 1500112, dtype: bool